version: '3'

services:
  app:
    build: .
    entrypoint: ./entrypoint.sh
    ports:
      - ${API_PORT}:${API_PORT}
    networks:
      - kong-net
    container_name: blog-data-replication
    volumes:
      - .:/home/node/app

networks:
  kong-net:
    external: true
